pt_BR: Translate help messages
Morganamilo/paru pull request #471
Opened 2021-07-18 02:00 UTC by keysym

2021-07-18 02:05 UTC, keysym commented
Pinging @DatCrazyDelphox and @ojmarcelino so they can help reviewing, if they want to!

2021-07-20 01:48 UTC, ojmarcelino requested changes

2021-07-20 11:55 UTC, keysym commented on po/pt_BR.po
> +"    --[no]newsonupgrade    Mostra novas notícias durante a atualização do "
Fixed! Great catch!

2021-07-20 12:07 UTC, ojmarcelino approved these changes

2021-07-23 09:16 UTC, Morganamilo commented on po/pt_BR.po
> +msgstr "    --mflags    <argumentos>    Passa argumentos para makepkg"
This breaks alignment.

2021-07-23 09:17 UTC, Morganamilo commented on po/pt_BR.po
> +"    --clonedir  <diretório>      Diretório usado para baixar e executar "
This breaks alignment.

2021-07-24 15:42 UTC, keysym commented
Fixed alignment:

```
Novas opções:
       --repo                   Assume que os alvos sejam dos repositórios
    -a --aur                    Assume que os alvos sejam do AUR
    --aururl    <url>           Define uma URL alternativa do AUR
    --clonedir  <diretório>     Diretório usado para baixar e executar PKGBUILDs

    --makepkg   <arquivo>       Comando makepkg a ser usado
    --mflags    <argumentos>    Passa argumentos para makepkg
    --pacman    <arquivo>       Comando pacman a ser usado
    --git       <arquivo>       Comando git a ser usado
    --gitflags  <argumentos>    Passa argumentos para git
    --sudo      <arquivo>       Comando sudo a ser usado
    --sudoflags <argumentos>    Passa argumentos para sudo
    --asp       <arquivo>       Comando asp a ser usado
    --bat       <arquivo>       Comando bat a ser usado
    --batflags  <argumentos>    Passa argumentos para bat
    --gpg       <arquivo>       Comando gpg a ser usado
    --gpgflags  <argumentos>    Passa argumentos para gpg
    --fm        <arquivo>       Gerenciador de arquivos a ser usado para revisão de PKGBUILD
    --fmflags   <argumentos>    Passa argumentos ao gerenciador de arquivos

```

2021-07-25 11:41 UTC, ojmarcelino approved these changes

2021-07-25 11:42 UTC, ojmarcelino approved these changes

2021-07-25 19:23 UTC, merged